[package]
authors = ["Philipp Korber <p.korber@1aim.com>"]
categories = []
description = "TODO"
documentation = "https://docs.rs/mail-codec"
keywords = ["mail", "codec", "mime", "smtp"]
license = "MIT OR Apache-2.0"
name = "mail-codec"
readme = "./README.md"
repository = "https://github.com/1aim/mail-codec"
version = "0.1.0"

[badges]

[badges.travis-ci]
branch = "master"
repository = "1aim/mail-codec"

[dependencies]
futures = "0.1.14"
log = "0.3.8"
rand = "0.3.15"
scoped-tls = "0.1.0"
serde = "1.0.10"
serde_derive = "1.0.10"
vec1 = { git="https://github.com/1aim/vec1" }
total-order-multi-map = { git="https://github.com/1aim/total-order-multi-map" }
mail-codec-core = { git="https://github.com/1aim/mail-codec-core" }
mail-codec-headers = { git="https://github.com/1aim/mail-codec-headers" }
error-chain = "0.11.0"
chrono = "0.4.0"
soft-ascii-string = "0.2.0"

[dependencies.mime]
git="https://github.com/1aim/mime"
branch="parser_revamp"
version="0.4.0"

[dependencies.tree_magic]
version = "0.2.0"
features = ["staticmime"]

[dependencies.futures-cpupool]
optional = true
version = "0.1.5"

[dev-dependencies]
serde_json = "1.0.2"

[features]
debug_trace_tokens = []
default = ["default_impl"]
default_impl = ["default_impl_mail", "default_impl_compose"]
default_impl_any = []
default_impl_component_id = ["default_impl_any"]
default_impl_compose = ["default_impl_name_composer", "default_impl_component_id"]
default_impl_cpupool = ["futures-cpupool", "default_impl_any"]
default_impl_fs = ["default_impl_any"]
default_impl_mail = ["default_impl_cpupool", "default_impl_fs", "default_impl_vfs"]
default_impl_name_composer = ["default_impl_any"]
default_impl_vfs = ["default_impl_any"]
traceing = [ "mail-codec-core/traceing", "mail-codec-headers/traceing" ]
